const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const api=async(path,opt={})=>{const r=await fetch(path,{credentials:'same-origin',...opt});if(r.status===401)throw Object.assign(new Error('UNAUTHORIZED'),{code:401});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP ${r.status}`);return r.status===204?null:r.json()};
const tabs=$$('[data-tab]'),panels=$$('.panel'),title=$('#pageTitle'),titles={dashboard:'Control Room',media:'Media & Gallery',frames:'Frame Studio',bookings:'Bookings',content:'Site Content',social:'Social Links',settings:'Settings'};
tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));panels.forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');title.textContent=titles[b.dataset.tab];if(b.dataset.tab==='bookings')loadBookings();if(b.dataset.tab==='media')loadMedia()});
async function session(){try{const me=await api('/api/admin/me');$('#adminEmail').textContent=me.email;return true}catch(e){if(e.code===401){$('#loginGate').hidden=false;document.body.classList.add('locked')}return false}}
let media=[],selected=null;
function frameValues(){return{frame_type:$('#frameType').value,position:$('#position').value,zoom:Number($('#zoom').value),radius:Number($('#radius').value),focus_x:Number($('#focusX').value),focus_y:Number($('#focusY').value)}}
function updateFrame(){const p=$('#framePreview');if(!p.src)return;const f=frameValues();const ratios={portrait:'4/5',landscape:'16/9',square:'1/1',story:'9/16',wide:'21/9','3x2':'3/2','4x3':'4/3',custom:'4/3'};p.style.aspectRatio=ratios[f.frame_type]||'16/10';p.style.objectFit=f.frame_type==='contain'?'contain':'cover';p.style.objectPosition=`${f.focus_x}% ${f.focus_y}%`;p.style.transform=`scale(${f.zoom})`;p.style.borderRadius=f.radius+'px';$('#zoomOut').textContent=f.zoom.toFixed(2)+'×';$('#radiusOut').textContent=f.radius+'px';$('#focusXOut').textContent=f.focus_x+'%';$('#focusYOut').textContent=f.focus_y+'%'}
['frameType','focusX','focusY','zoom','radius','position'].forEach(x=>$('#'+x).addEventListener('input',updateFrame));
function renderMedia(){const q=$('#mediaSearch').value.toLowerCase(),filter=$('#mediaFilter').value,g=$('#mediaGrid');g.innerHTML='';media.filter(m=>(!q||`${m.name} ${m.caption||''}`.toLowerCase().includes(q))&&(filter==='all'||filter==='published'&&m.published||filter==='draft'&&!m.published||filter==='image'&&m.mime_type.startsWith('image/')||filter==='video'&&m.mime_type.startsWith('video/'))).forEach(m=>{const el=document.createElement('article');el.className='media-item';el.innerHTML=`<div class="thumb">${m.mime_type.startsWith('video/')?`<video src="${m.public_url}" muted playsinline></video>`:`<img src="${m.public_url}" alt="">`}</div><div class="media-meta"><b>${escapeHtml(m.name)}</b><small>${m.published?'LIVE':'DRAFT'} · ${Math.round((m.size||0)/1024)} KB</small><div class="media-actions"><button data-id="${m.id}" class="edit-frame">Frame</button><button data-id="${m.id}" class="toggle-publish">${m.published?'Unpublish':'Publish'}</button></div></div>`;g.appendChild(el)});$('#mediaCount').textContent=media.length;$('#publishedCount').textContent=media.filter(x=>x.published).length}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadMedia(){try{media=(await api('/api/admin/media')).results||[];renderMedia()}catch(e){if(e.code!==401)$('#mediaGrid').innerHTML='<p class="empty">Unable to load media.</p>'}}
$('#mediaGrid').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const m=media.find(x=>x.id===b.dataset.id);if(!m)return;if(b.classList.contains('edit-frame')){selected=m;$('#framePreview').src=m.public_url;$('#frameType').value=m.frame_type||'cover';$('#position').value=m.position||'center';$('#zoom').value=m.zoom||1;$('#radius').value=m.radius||18;$('#focusX').value=m.focus_x||50;$('#focusY').value=m.focus_y||50;updateFrame();tabs.find(x=>x.dataset.tab==='frames').click()}else if(b.classList.contains('toggle-publish')){await api(`/api/admin/media/${m.id}/publish`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({published:!m.published})});await loadMedia()}});
$('#fileInput').onchange=async()=>{for(const file of $('#fileInput').files){const fd=new FormData();fd.append('file',file);try{await api('/api/admin/media',{method:'POST',body:fd})}catch(e){alert(`${file.name}: ${e.message}`)}}$('#fileInput').value='';await loadMedia()};$('#mediaSearch').oninput=renderMedia;$('#mediaFilter').onchange=renderMedia;
$('#saveFrame').onclick=async()=>{if(!selected)return $('#frameMsg').textContent='Select a media item first.';const f=frameValues();await api(`/api/admin/media/${selected.id}/frame`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(f)});Object.assign(selected,f);$('#frameMsg').textContent='Saved to CMS.';setTimeout(()=>$('#frameMsg').textContent='',1800)};
async function loadBookings(){try{const d=await api('/api/admin/bookings');const rows=d.results||[];$('#bookingCount').textContent=rows.filter(x=>x.status==='pending').length;$('#bookingList').innerHTML=rows.length?rows.map(x=>`<article class="booking-row"><div><b>${escapeHtml(x.name)}</b><span>${escapeHtml(x.phone)} · ${escapeHtml(x.service||'Service')}</span></div><small>${escapeHtml(x.preferred_date||'Flexible')} · ${new Date(x.created_at).toLocaleString()}</small><p>${escapeHtml(x.message||'')}</p></article>`).join(''):'<p class="empty">No booking requests.</p>'}catch(e){if(e.code!==401)$('#bookingList').innerHTML='<p class="empty">Unable to load bookings.</p>'}}
$('#refreshBookings').onclick=loadBookings;
async function loadSetting(key,form){try{const d=await api('/api/admin/'+key);if(d?.value){const x=JSON.parse(d.value);Object.entries(x).forEach(([k,v])=>{const el=form.elements[k];if(el)el.value=v})}}catch(e){}}
$('#contentForm').onsubmit=async e=>{e.preventDefault();await api('/api/admin/content',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});$('#contentMsg').textContent='Saved.'};$('#socialForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));await api('/api/admin/social',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(x)});$('#socialMsg').textContent='Saved. Footer will use these links.'};
$('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.href='/'};
loadSetting('content',$('#contentForm'));loadSetting('social',$('#socialForm'));session().then(ok=>ok&&loadMedia());if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');