const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});const cors=(h={})=>({...h,'x-content-type-options':'nosniff'});const id=()=>crypto.randomUUID();const now=()=>new Date().toISOString();
async function accessToken(env){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,refresh_token:env.GOOGLE_REFRESH_TOKEN,grant_type:'refresh_token'})});if(!r.ok)throw new Error('Google OAuth token refresh failed');return(await r.json()).access_token}
async function driveUpload(env,file){const token=await accessToken(env);const meta={name:file.name,parents:[env.DRIVE_FOLDER_ID],description:'Security Vision gallery media'};const boundary='sv_'+crypto.randomUUID().replaceAll('-','');const enc=new TextEncoder(),head=enc.encode(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: ${file.type||'application/octet-stream'}\r\n\r\n`),bytes=new Uint8Array(await file.arrayBuffer()),tail=enc.encode(`\r\n--${boundary}--`),body=new Uint8Array(head.length+bytes.length+tail.length);body.set(head);body.set(bytes,head.length);body.set(tail,head.length+bytes.length);const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,webContentLink,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});if(!r.ok)throw new Error('Google Drive upload failed');const out=await r.json();const p=await fetch(`https://www.googleapis.com/drive/v3/files/${out.id}/permissions`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({role:'reader',type:'anyone'})});if(!p.ok)throw new Error('Google Drive permission update failed');return out}
async function requireAuth(request,env){const c=request.headers.get('Cookie')||'',m=c.match(/sv_session=([^;]+)/);if(!m)return null;return env.DB.prepare('SELECT * FROM sessions WHERE id=? AND expires_at>?').bind(m[1],Date.now()).first()}
async function publicData(env){const media=await env.DB.prepare('SELECT id,name,mime_type,public_url,alt,caption,category,frame_type,position,focus_x,focus_y,zoom,radius,sort_order FROM media WHERE published=1 ORDER BY sort_order ASC,created_at DESC').all();const settings=await env.DB.prepare('SELECT key,value FROM settings').all();return{media:media.results||[],settings:Object.fromEntries((settings.results||[]).map(x=>{try{return[x.key,JSON.parse(x.value)]}catch{return[x.key,{}]}}))}}
export default{async fetch(request,env){const url=new URL(request.url),path=url.pathname;try{
if(request.method==='GET'&&path==='/api/site')return json(await publicData(env));
if(request.method==='POST'&&path==='/api/bookings'){const x=await request.json();if(!x.name||!x.phone)return json({error:'Name and phone are required'},400);const b={id:id(),name:String(x.name).slice(0,100),phone:String(x.phone).slice(0,40),service:String(x.service||'').slice(0,100),preferred_date:String(x.date||'').slice(0,20),message:String(x.message||'').slice(0,1000),status:'pending',created_at:now()};await env.DB.prepare('INSERT INTO bookings(id,name,phone,service,preferred_date,message,status,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(...Object.values(b)).run();return json({ok:true,id:b.id},201)}
if(path==='/api/admin/auth/google'&&request.method==='GET'){const state=id(),u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',env.GOOGLE_CLIENT_ID);u.searchParams.set('redirect_uri',`${env.PUBLIC_ORIGIN}/api/admin/auth/callback`);u.searchParams.set('response_type','code');u.searchParams.set('scope','openid email');u.searchParams.set('state',state);u.searchParams.set('access_type','offline');return new Response(null,{status:302,headers:{Location:u.toString(),'Set-Cookie':`sv_oauth_state=${state}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=600`}})}
if(path==='/api/admin/auth/callback'&&request.method==='GET'){const code=url.searchParams.get('code'),state=url.searchParams.get('state'),cookie=request.headers.get('Cookie')||'',sm=cookie.match(/sv_oauth_state=([^;]+)/);if(!code||!state||!sm||sm[1]!==state)return new Response('Invalid OAuth state',400);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,code,grant_type:'authorization_code',redirect_uri:`${env.PUBLIC_ORIGIN}/api/admin/auth/callback`})});if(!r.ok)return new Response('OAuth exchange failed',401);const tok=await r.json(),me=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${tok.access_token}`}}),profile=await me.json();if(!profile.email||profile.email.toLowerCase()!==env.ADMIN_GOOGLE_EMAIL.toLowerCase())return new Response('Not authorized',403);const sid=id();await env.DB.prepare('INSERT INTO sessions(id,email,expires_at,created_at) VALUES(?,?,?,?)').bind(sid,profile.email,Date.now()+43200000,Date.now()).run();return new Response(null,{status:302,headers:{Location:`${env.PUBLIC_ORIGIN}/sv-control-7f3a9d/`,'Set-Cookie':`sv_session=${sid}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`}})}
if(!path.startsWith('/api/admin/'))return env.ASSETS.fetch(request);const session=await requireAuth(request,env);if(!session)return json({error:'Unauthorized'},401);
if(path==='/api/admin/logout'&&request.method==='POST'){const c=request.headers.get('Cookie')||'',m=c.match(/sv_session=([^;]+)/);if(m)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(m[1]).run();return new Response(null,{status:204,headers:{'Set-Cookie':'sv_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'}})}
if(path==='/api/admin/me'&&request.method==='GET')return json({email:session.email});
if(path==='/api/admin/media'&&request.method==='GET')return json(await env.DB.prepare('SELECT * FROM media ORDER BY sort_order ASC,created_at DESC').all());
if(path==='/api/admin/media'&&request.method==='POST'){const form=await request.formData(),file=form.get('file');if(!(file instanceof File))return json({error:'file required'},400);if(file.size>25*1024*1024)return json({error:'File too large (25MB max)'},413);if(!/^(image\/(jpeg|png|webp|gif)|video\/(mp4|webm|quicktime))$/.test(file.type))return json({error:'Unsupported media type'},415);const d=await driveUpload(env,file),item={id:id(),drive_file_id:d.id,name:file.name,mime_type:file.type,size:file.size,public_url:`https://drive.google.com/uc?id=${d.id}&export=view`,alt:String(form.get('alt')||file.name).slice(0,200),caption:String(form.get('caption')||'').slice(0,500),category:String(form.get('category')||'gallery').slice(0,50),created_at:now()};await env.DB.prepare('INSERT INTO media(id,drive_file_id,name,mime_type,size,public_url,alt,caption,category,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(...Object.values(item)).run();return json(item,201)}
const fm=path.match(/^\/api\/admin\/media\/([^/]+)\/frame$/);if(fm&&request.method==='PATCH'){const x=await request.json();await env.DB.prepare('UPDATE media SET frame_type=?,position=?,focus_x=?,focus_y=?,zoom=?,radius=? WHERE id=?').bind(String(x.frame_type||'cover'),String(x.position||'center'),Math.max(0,Math.min(100,Number(x.focus_x??50))),Math.max(0,Math.min(100,Number(x.focus_y??50))),Math.max(1,Math.min(2.5,Number(x.zoom??1))),Math.max(0,Math.min(40,Number(x.radius??18))),fm[1]).run();return json({ok:true})}
const pub=path.match(/^\/api\/admin\/media\/([^/]+)\/publish$/);if(pub&&request.method==='POST'){const x=await request.json();await env.DB.prepare('UPDATE media SET published=? WHERE id=?').bind(x.published?1:0,pub[1]).run();return json({ok:true})}
if(path==='/api/admin/bookings'&&request.method==='GET')return json(await env.DB.prepare('SELECT * FROM bookings ORDER BY created_at DESC').all());
for(const key of ['content','social'])if(path===`/api/admin/${key}`&&(request.method==='GET'||request.method==='PUT')){if(request.method==='GET')return json(await env.DB.prepare(`SELECT key,value FROM settings WHERE key=?`).bind(key).first());const x=await request.json();await env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,JSON.stringify(x)).run();return json({ok:true})}
return json({error:'Not found'},404)}catch(e){return json({error:e.message||'Server error'},500)}}};